2021-12-15 09:24:45,987 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 09:24:49,017 ERROR: Exception on / [GET] [in C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\routes.py", line 113, in before_request
    if current_user.is_authenticated:
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2021-12-15 09:24:49,231 ERROR: Exception on /favicon.ico [GET] [in C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 1948, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask\app.py", line 2242, in preprocess_request
    rv = func()
  File "C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\routes.py", line 113, in before_request
    if current_user.is_authenticated:
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\KOSCOM\anaconda3\lib\site-packages\flask_login\login_manager.py", line 302, in _load_user
    raise Exception(
Exception: Missing user_loader or request_loader. Refer to http://flask-login.readthedocs.io/#how-it-works for more info.
2021-12-15 09:51:24,990 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 09:53:42,907 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 09:53:55,040 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 09:54:05,929 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 11:36:23,017 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 13:24:23,524 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 16:01:09,568 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
2021-12-15 16:18:06,176 INFO: Microblog startup [in C:\Users\KOSCOM\Desktop\jupyterlab\Flask\microblog\app\__init__.py:57]
